In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('Sub2Sys_strings.csv')
df.head()

,Function,Failure Condition_1s,Failure Condition_2s,Parent Condition_1s,Parent Condition_2s,DAL
0,A,Partial Failure,Annuciated,Partial Failure,Annuciated,0
1,A,Total Failure,Annuciated,Partial Failure,Annuciated,1
2,B,Partial Failure,Annuciated,Partial Failure,Annuciated,0
3,B,Total Failure,Annuciated,Partial Failure,Annuciated,1
4,C,Partial Failure,Annuciated,Partial Failure,Annuciated,0

In [5]:
df['DAL'] = df.DAL.apply(lambda x: 'Catastrophic' if x==4 else x)
df.head()

,Function,Failure Condition_1s,Failure Condition_2s,Parent Condition_1s,Parent Condition_2s,DAL
0,A,Partial Failure,Annuciated,Partial Failure,Annuciated,0
1,A,Total Failure,Annuciated,Partial Failure,Annuciated,1
2,B,Partial Failure,Annuciated,Partial Failure,Annuciated,0
3,B,Total Failure,Annuciated,Partial Failure,Annuciated,1
4,C,Partial Failure,Annuciated,Partial Failure,Annuciated,0

In [6]:
df['DAL'] = df.DAL.apply(lambda x: 'Hazardous' if x==3 else x)
df.head()

,Function,Failure Condition_1s,Failure Condition_2s,Parent Condition_1s,Parent Condition_2s,DAL
0,A,Partial Failure,Annuciated,Partial Failure,Annuciated,0
1,A,Total Failure,Annuciated,Partial Failure,Annuciated,1
2,B,Partial Failure,Annuciated,Partial Failure,Annuciated,0
3,B,Total Failure,Annuciated,Partial Failure,Annuciated,1
4,C,Partial Failure,Annuciated,Partial Failure,Annuciated,0

In [7]:
df['DAL'] = df.DAL.apply(lambda x: 'Major' if x==2 else x)
df.head()

,Function,Failure Condition_1s,Failure Condition_2s,Parent Condition_1s,Parent Condition_2s,DAL
0,A,Partial Failure,Annuciated,Partial Failure,Annuciated,0
1,A,Total Failure,Annuciated,Partial Failure,Annuciated,1
2,B,Partial Failure,Annuciated,Partial Failure,Annuciated,0
3,B,Total Failure,Annuciated,Partial Failure,Annuciated,1
4,C,Partial Failure,Annuciated,Partial Failure,Annuciated,0

In [8]:
df['DAL'] = df.DAL.apply(lambda x: 'Minor' if x==1 else x)
df.head()

,Function,Failure Condition_1s,Failure Condition_2s,Parent Condition_1s,Parent Condition_2s,DAL
0,A,Partial Failure,Annuciated,Partial Failure,Annuciated,0
1,A,Total Failure,Annuciated,Partial Failure,Annuciated,Minor
2,B,Partial Failure,Annuciated,Partial Failure,Annuciated,0
3,B,Total Failure,Annuciated,Partial Failure,Annuciated,Minor
4,C,Partial Failure,Annuciated,Partial Failure,Annuciated,0

In [9]:
df['DAL'] = df.DAL.apply(lambda x: 'None' if x==0 else x)
df.head()

,Function,Failure Condition_1s,Failure Condition_2s,Parent Condition_1s,Parent Condition_2s,DAL
0,A,Partial Failure,Annuciated,Partial Failure,Annuciated,None
1,A,Total Failure,Annuciated,Partial Failure,Annuciated,Minor
2,B,Partial Failure,Annuciated,Partial Failure,Annuciated,None
3,B,Total Failure,Annuciated,Partial Failure,Annuciated,Minor
4,C,Partial Failure,Annuciated,Partial Failure,Annuciated,None

In [11]:
df.to_csv('Sub2Sys_string.csv',index=False)